export default [
  {
    indicatorType: 'scoresTotal',
    significance: 50,
    cycles: [
      {
        cycle: 1,
        isClosed: true,
        significance: 0,
        objective: 1,
        directSale: 32,
        naturaNetwork: 233,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 2,
        isClosed: true,
        significance: 0,
        objective: 233,
        directSale: 213,
        naturaNetwork: 1233,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 3,
        isClosed: true,
        significance: 0,
        objective: 12333,
        directSale: 123123,
        naturaNetwork: 323,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 4,
        isClosed: true,
        significance: 0,
        objective: 123,
        directSale: 123,
        naturaNetwork: 12333,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 5,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
        current: true,
      },
      {
        cycle: 6,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 7,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 8,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 9,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 10,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 11,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 12,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 13,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 14,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 15,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 16,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 17,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 18,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 19,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
    ],
  },
  {
    indicatorType: 'registration',
    significance: 30,
    cycles: [
      {
        cycle: 1,
        isClosed: true,
        significance: 0,
        objective: 1,
        directSale: 32,
        naturaNetwork: 233,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 2,
        isClosed: true,
        significance: 0,
        objective: 233,
        directSale: 213,
        naturaNetwork: 1233,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 3,
        isClosed: true,
        significance: 0,
        objective: 12333,
        directSale: 123123,
        naturaNetwork: 323,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 4,
        isClosed: true,
        significance: 0,
        objective: 123,
        directSale: 123,
        naturaNetwork: 12333,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 5,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
        current: true,
      },
      {
        cycle: 6,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 7,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 8,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 9,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 10,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 11,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 12,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 13,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 14,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 15,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 16,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 17,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 18,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 19,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
    ],
  },
  {
    indicatorType: 'active',
    significance: 20,
    cycles: [
      {
        cycle: 1,
        isClosed: true,
        significance: 0,
        objective: 1,
        directSale: 32,
        naturaNetwork: 233,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 2,
        isClosed: true,
        significance: 0,
        objective: 233,
        directSale: 213,
        naturaNetwork: 1233,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 3,
        isClosed: true,
        significance: 0,
        objective: 12333,
        directSale: 123123,
        naturaNetwork: 323,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 4,
        isClosed: true,
        significance: 0,
        objective: 123,
        directSale: 123,
        naturaNetwork: 12333,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 5,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
        current: true,
      },
      {
        cycle: 6,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 7,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 8,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 9,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 10,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 11,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 12,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 13,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 14,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 15,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 16,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 17,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 18,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
      {
        cycle: 19,
        significance: 0,
        objective: 123,
        directSale: 0,
        naturaNetwork: 0,
        overcoming: 0,
        value: 'string',
        consolidated: {
          overcoming: 0,
          value: 'string',
        },
      },
    ],
  },
];
