version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build:staging
      - run:
          name: Install react-deploy-s3
          command: sudo npm i -g react-deploy-s3
      - run:
          name: Deploy to AWS using react-deploy-s3
          command: react-deploy-s3 deploy --access-key-id $AWS_KEY --secret-access-key $AWS_SECRET --bucket $BUCKET --region $REGION --distribution-id $DIST_ID

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - staging
