version: "3"
services:
  web:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    environment:
      SSH_AUTH_SOCK: "$SSH_AUTH_SOCK"
    ports:
      - 3000:3000
    volumes:
      - .:/app
